import { useMutation, useQuery } from "@tanstack/react-query";
import { ArrowRight, Download, ExternalLink, GitCompare, LoaderCircle, SearchCheck, ShieldCheck, TriangleAlert } from "lucide-react";
import { Link } from "react-router-dom";
import { api } from "../lib/api";
import { cn, formatRelative } from "../lib/utils";
import type { EvidenceBundle, Incident } from "../types";

function downloadBundle(bundle: EvidenceBundle) {
  const url = URL.createObjectURL(new Blob([JSON.stringify(bundle, null, 2)], { type:"application/json" }));
  const anchor = document.createElement("a"); anchor.href=url; anchor.download=`${bundle.code.toLowerCase()}-evidence-${bundle.evidenceRevision.slice(0,10)}.json`; anchor.click(); URL.revokeObjectURL(url);
}

export function DebuggingInsights({ incident, onSelectEvent }: { incident: Incident; onSelectEvent(eventId: string): void }) {
  const intelligence = useQuery({ queryKey:["intelligence",incident.id,incident.evidenceRevision], queryFn:()=>api.intelligence(incident.id) });
  const bundle = useMutation({ mutationFn:()=>api.evidenceBundle(incident.id), onSuccess:downloadBundle });
  if (intelligence.isLoading) return <section className="surface-lined flex min-h-40 items-center justify-center text-sm text-muted"><LoaderCircle className="mr-2 h-4 w-4 animate-spin" />Comparing retained evidence</section>;
  if (intelligence.error || !intelligence.data) return <section className="surface-lined p-5 text-sm text-danger">Debugging comparisons are unavailable. <button className="font-semibold underline" onClick={()=>void intelligence.refetch()}>Retry</button></section>;
  const data=intelligence.data;
  return <section className="surface-lined overflow-hidden" aria-labelledby="debugging-value-title">
    <div className="flex flex-wrap items-start justify-between gap-4 px-5 py-5 sm:px-6"><div><h2 id="debugging-value-title" className="font-heading text-xl font-semibold tracking-[-.025em]">Debugging evidence</h2><p className="mt-1 max-w-3xl text-sm leading-6 text-muted">Compare failing requests, inspect recent changes, reuse prior learning carefully, and export a redacted evidence packet.</p></div><button className="control-secondary inline-flex items-center gap-2" disabled={bundle.isPending} onClick={()=>bundle.mutate()}>{bundle.isPending?<LoaderCircle className="h-4 w-4 animate-spin"/>:<Download className="h-4 w-4"/>}Redacted bundle</button></div>
    <div className="grid border-t border-line xl:grid-cols-2">
      <article className="border-b border-line p-5 sm:p-6 xl:border-r"><div className="flex items-center gap-2"><GitCompare className="h-4 w-4 text-info"/><h3 className="section-title">Healthy vs failing requests</h3></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-control bg-elevated p-4"><p className="text-xs text-muted">Healthy sample</p><p className="measurement-number mt-1 text-2xl font-semibold">{data.cohorts.healthy.sampleCount}</p><p className="mt-1 text-xs text-muted">median {data.cohorts.healthy.medianDurationMs ?? "—"}ms</p></div><div className="rounded-control bg-elevated p-4"><p className="text-xs text-muted">Failing sample</p><p className="measurement-number mt-1 text-2xl font-semibold">{data.cohorts.failing.sampleCount}</p><p className="mt-1 text-xs text-muted">median {data.cohorts.failing.medianDurationMs ?? "—"}ms</p></div></div><div className="mt-4 flex flex-wrap gap-2">{data.cohorts.routes.map((item)=><span key={item} className="rounded-full bg-elevated px-2.5 py-1 text-xs font-semibold">route {item}</span>)}{data.cohorts.releases.map((item)=><span key={item} className="rounded-full bg-elevated px-2.5 py-1 text-xs font-semibold">release {item}</span>)}</div><ul className="mt-4 space-y-1">{data.cohorts.limitations.map((item)=><li key={item} className="flex gap-2 text-xs leading-5 text-muted"><TriangleAlert className="mt-.5 h-3.5 w-3.5 shrink-0 text-warning"/>{item}</li>)}</ul></article>
      <article className="border-b border-line p-5 sm:p-6"><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-info"/><h3 className="section-title">Measured customer impact</h3></div>{data.impact.measured?<div className="mt-4"><p className="measurement-number text-2xl font-semibold">{data.impact.failedRequests} / {data.impact.totalRequests}</p><p className="mt-1 text-sm text-muted">{((data.impact.rate??0)*100).toFixed(2)}% observed failure rate · {data.impact.source}</p></div>:<div className="mt-4 rounded-control bg-warning/10 p-4"><p className="text-sm font-semibold text-warning">Denominator unknown</p><p className="mt-1 text-xs leading-5 text-muted">{data.impact.failedRequests ?? 0} retained failing samples cannot establish customer impact without total attempts.</p></div>}<ul className="mt-4 space-y-1">{data.impact.unknowns.map((item)=><li key={item} className="text-xs leading-5 text-muted">• {item}</li>)}</ul></article>
      <article className="border-b border-line p-5 sm:p-6 xl:border-b-0 xl:border-r"><h3 className="section-title">Recent changes</h3><p className="mt-1 text-xs text-muted">Correlation candidates—not asserted causes.</p><div className="mt-4 space-y-3">{data.changes.map((change)=><button key={change.eventId} className="block w-full rounded-control bg-elevated p-4 text-left hover:bg-line/45" onClick={()=>onSelectEvent(change.eventId)}><div className="flex items-center justify-between gap-3"><p className="text-sm font-semibold">{change.title}</p><span className="measurement-number text-xs uppercase text-muted">{change.type}</span></div><p className="mt-1 text-xs text-muted">{change.service} · {formatRelative(change.timestamp)}{change.version?` · ${change.version}`:""}</p><p className="mt-2 text-xs leading-5 text-success">For: {change.evidenceFor}</p><p className="mt-1 text-xs leading-5 text-warning">Against: {change.evidenceAgainst}</p></button>)}{!data.changes.length&&<p className="rounded-control bg-elevated p-4 text-sm text-muted">No deployment, flag, schema, configuration, or infrastructure change is retained in this window.</p>}</div></article>
      <article className="p-5 sm:p-6"><h3 className="section-title">Useful next-test queries</h3><div className="mt-4 space-y-3">{data.querySuggestions.map((item)=><div key={item.id} className="rounded-control bg-elevated p-4"><div className="flex items-center justify-between gap-3"><p className="text-sm font-semibold">{item.label}</p><span className="text-xs text-muted">{item.source}</span></div><code className="mt-3 block overflow-x-auto rounded bg-panel p-2 text-xs">{item.query}</code><p className="mt-2 text-xs leading-5 text-muted">{item.limitation}</p></div>)}</div></article>
    </div>
    <div className="border-t border-line px-5 py-5 sm:px-6"><h3 className="section-title">Similar past investigations</h3><div className="mt-4 grid gap-3 lg:grid-cols-2">{data.comparisons.map((item)=><Link key={item.incidentId} to={`/incidents/${item.incidentId}?area=handoff`} className="group rounded-control bg-elevated p-4 hover:bg-line/45"><div className="flex items-center justify-between gap-3"><p className="text-sm font-semibold">{item.code} · {item.title}</p><ArrowRight className="h-4 w-4 text-faint transition-transform group-hover:translate-x-1"/></div><p className="mt-2 text-xs text-success">Similar: {item.similarities[0]}</p><p className="mt-1 text-xs text-warning">Different: {item.differences[0] ?? "No retained structural difference"}</p><p className="mt-2 text-xs leading-5 text-muted">{item.applicability}</p></Link>)}{!data.comparisons.length&&<p className="text-sm text-muted">No same-service historical investigation has enough comparable evidence.</p>}</div></div>
    {bundle.error&&<p role="alert" className="border-t border-line px-5 py-3 text-sm text-danger">{bundle.error.message}</p>}
  </section>;
}
