import { randomUUID } from "node:crypto";
import { Pool, type PoolClient } from "pg";
import { config } from "./config.js";
import { repository } from "./repository.js";
import type { Incident, WorkspaceRole } from "./types.js";

export type CheckStatus = "planned" | "running" | "supported" | "disproved" | "inconclusive";
export type ValidationKind = "ci" | "manual" | "isolated_http";
export type ValidationStatus = "passed" | "failed" | "unsupported";
export type RecoveryKind = "runtime" | "delivery";

export interface InvestigationCheck {
  id: string; incidentId: string; templateId: string; title: string; question: string; method: string;
  expectedSignal: string; conditions: string; result: string; status: CheckStatus; assignee: string;
  evidenceIds: string[]; evidenceRevision: string; conclusionState: "current" | "needs_recheck";
  createdAt: string; updatedAt: string;
}

export interface ChangeProposal {
  id: string; incidentId: string; version: number; supersedesId: string | null; title: string; change: string;
  rollbackPlan: string; target: Record<string, unknown>; evidenceRevision: string; createdBy: string; createdAt: string;
}

export interface ValidationArtifact {
  id: string; incidentId: string; proposalId: string; proposalVersion: number; kind: ValidationKind; status: ValidationStatus;
  summary: string; provenance: Record<string, unknown>; evidenceRevision: string; createdBy: string; createdAt: string;
}
export interface ProposalReview { id:string; incidentId:string; proposalId:string; proposalVersion:number; requestedBy:string; reviewedBy:string|null; status:"pending"|"approved"|"rejected"; reason:string; evidenceRevision:string; createdAt:string; reviewedAt:string|null }

export interface RecoveryCriterion {
  id: string; incidentId: string; version: number; kind: RecoveryKind; name: string; source: string; query: string;
  unit: string; comparison: "lte" | "gte"; targetValue: number; minConsecutiveWindows: number;
  maxAgeMinutes: number; observationMinutes: number; deliveryIdentity: Record<string, unknown> | null;
  createdAt: string;
}

export interface TypedMeasurement {
  id: string; incidentId: string; criterionId: string; value: number | null; unit: string; source: string; query: string;
  windowStartedAt: string; windowEndedAt: string; observedAt: string; state: "valid" | "missing" | "invalid";
  note: string; createdAt: string;
}

export interface RecoveryEvaluation {
  state: "verified" | "failed" | "insufficient" | "stale";
  reason: string; criterionVersion: number | null; evaluatedAt: string; supportingMeasurementIds: string[];
}

export interface CaseworkSnapshot {
  caseKind: "delivery" | "runtime" | "uncertain";
  checks: InvestigationCheck[]; proposals: ChangeProposal[]; validations: ValidationArtifact[]; reviews:ProposalReview[];
  criteria: RecoveryCriterion[]; measurements: TypedMeasurement[]; recovery: RecoveryEvaluation;
  evidenceReview: { reviewedRevision: string | null; currentRevision: string; changed: boolean; affectedCheckIds: string[] };
}

const iso = (value: unknown) => new Date(String(value)).toISOString();
const clone = <T>(value: T): T => structuredClone(value);
const passes = (criterion: RecoveryCriterion, measurement: TypedMeasurement) => measurement.value !== null
  && measurement.unit === criterion.unit
  && (criterion.comparison === "lte" ? measurement.value <= criterion.targetValue : measurement.value >= criterion.targetValue);

export function evaluateRuntimeRecovery(criterion: RecoveryCriterion | undefined, measurements: TypedMeasurement[], now = new Date()): RecoveryEvaluation {
  if (!criterion) return { state:"insufficient", reason:"Define a versioned runtime recovery criterion before monitoring.", criterionVersion:null, evaluatedAt:now.toISOString(), supportingMeasurementIds:[] };
  const relevant = measurements.filter((item) => item.criterionId === criterion.id).sort((a,b) => b.observedAt.localeCompare(a.observedAt));
  if (!relevant.length) return { state:"insufficient", reason:"No runtime measurements have been recorded for this criterion.", criterionVersion:criterion.version, evaluatedAt:now.toISOString(), supportingMeasurementIds:[] };
  const newest = relevant[0]!;
  if (newest.state !== "valid") return { state:"insufficient", reason:"The newest measurement is missing or invalid.", criterionVersion:criterion.version, evaluatedAt:now.toISOString(), supportingMeasurementIds:[newest.id] };
  const ageMinutes = (now.getTime() - Date.parse(newest.observedAt)) / 60_000;
  if (ageMinutes > criterion.maxAgeMinutes) return { state:"stale", reason:`The newest measurement is ${Math.round(ageMinutes)} minutes old; the limit is ${criterion.maxAgeMinutes}.`, criterionVersion:criterion.version, evaluatedAt:now.toISOString(), supportingMeasurementIds:[newest.id] };
  const consecutive = relevant.slice(0, criterion.minConsecutiveWindows);
  const newestFailure = relevant.find((item) => item.state === "valid" && !passes(criterion, item));
  if (newestFailure && Date.parse(newestFailure.observedAt) >= Date.parse(consecutive.at(-1)?.observedAt ?? newest.observedAt)) {
    return { state:"failed", reason:"A newer applicable measurement is outside the recovery threshold.", criterionVersion:criterion.version, evaluatedAt:now.toISOString(), supportingMeasurementIds:[newestFailure.id] };
  }
  if (consecutive.length < criterion.minConsecutiveWindows || !consecutive.every((item) => item.state === "valid" && passes(criterion,item))) {
    return { state:"insufficient", reason:`Need ${criterion.minConsecutiveWindows} consecutive passing windows; ${consecutive.filter((item)=>item.state === "valid" && passes(criterion,item)).length} are currently available.`, criterionVersion:criterion.version, evaluatedAt:now.toISOString(), supportingMeasurementIds:consecutive.map((item)=>item.id) };
  }
  const observedMinutes = (Date.parse(consecutive[0]!.windowEndedAt) - Date.parse(consecutive.at(-1)!.windowStartedAt)) / 60_000;
  if (observedMinutes < criterion.observationMinutes) return { state:"insufficient", reason:`Passing windows cover ${Math.max(0,Math.round(observedMinutes))} minutes; ${criterion.observationMinutes} are required.`, criterionVersion:criterion.version, evaluatedAt:now.toISOString(), supportingMeasurementIds:consecutive.map((item)=>item.id) };
  return { state:"verified", reason:"The newest consecutive runtime windows satisfy the versioned recovery criterion.", criterionVersion:criterion.version, evaluatedAt:now.toISOString(), supportingMeasurementIds:consecutive.map((item)=>item.id) };
}

export function evaluateDeliveryRecovery(criterion: RecoveryCriterion | undefined, validations: ValidationArtifact[], now = new Date()): RecoveryEvaluation {
  if (!criterion) return { state:"insufficient", reason:"Define an exact delivery recovery criterion before monitoring.", criterionVersion:null, evaluatedAt:now.toISOString(), supportingMeasurementIds:[] };
  const required = criterion.deliveryIdentity ?? {};
  const matches = validations.filter((item) => item.kind === "ci" && Object.entries(required).every(([key,value]) => item.provenance[key] === value)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
  if (!matches.length) return { state:"insufficient", reason:"No CI rerun matches the required repository, workflow, ref, SHA, and attempt identity.", criterionVersion:criterion.version, evaluatedAt:now.toISOString(), supportingMeasurementIds:[] };
  const latest = matches[0]!;
  return { state:latest.status === "passed" ? "verified" : "failed", reason:latest.status === "passed" ? "The exact delivery workflow rerun passed. This verifies delivery only, not runtime health." : "The latest exact delivery workflow rerun did not pass.", criterionVersion:criterion.version, evaluatedAt:now.toISOString(), supportingMeasurementIds:[latest.id] };
}

const templates = [
  { id:"compare-cohort", title:"Compare failing and healthy requests", question:"Which request dimension separates failures from healthy traffic?", method:"Compare the same route, method, region, release, and time window.", expectedSignal:"A trace-backed delta with sample counts and comparable windows." },
  { id:"inspect-change", title:"Inspect the latest relevant change", question:"Did code, config, schema, flag, or infrastructure change before the symptom?", method:"Open the source change and compare its timestamp, target service, and environment.", expectedSignal:"A matching change with evidence for and against causal relevance." },
  { id:"trace-path", title:"Trace one failing request end to end", question:"Where does the first verified error or latency jump occur?", method:"Follow retained parent/child spans and record the first failing boundary.", expectedSignal:"A source-linked span boundary or an explicit trace coverage gap." },
  { id:"query-runtime", title:"Run a scoped runtime query", question:"Does the suspected failure persist for the affected service and environment?", method:"Run a source query with service, environment, route, and incident time range filled in.", expectedSignal:"A typed measurement with unit, interval, source, and freshness." },
  { id:"reproduce-http", title:"Reproduce one bounded HTTP failure", question:"Can the captured request reproduce against a specified version in isolation?", method:"Use a redacted request, controlled dependencies, explicit assertions, and a loopback-only target.", expectedSignal:"Preserved inputs and outputs, or an honest unsupported result." }
] as const;

type MemoryState = { checks: InvestigationCheck[]; proposals: ChangeProposal[]; validations: ValidationArtifact[]; reviews:ProposalReview[]; criteria: RecoveryCriterion[]; measurements: TypedMeasurement[]; cursors: Map<string,string>; resolutions: Array<Record<string,unknown>> };

export class CaseworkService {
  private pool: Pool | null;
  private memory: MemoryState = { checks:[], proposals:[], validations:[], reviews:[], criteria:[], measurements:[], cursors:new Map(), resolutions:[] };
  constructor(connectionString = config.databaseUrl) { this.pool = connectionString ? new Pool({ connectionString, ssl:connectionString.includes("localhost") ? false : { rejectUnauthorized:false }, max:4 }) : null; }
  async initialize() {
    if (!this.pool) return;
    await this.pool.query(`
      create table if not exists investigation_checks (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, incident_id uuid not null references incidents(id) on delete cascade, template_id text not null, title text not null, question text not null, method text not null, expected_signal text not null, conditions text not null, result text not null default '', status text not null, assignee text not null, evidence_ids uuid[] not null default '{}', evidence_revision timestamptz not null, conclusion_state text not null default 'current', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
      create table if not exists evidence_review_cursors (organization_id uuid not null references organizations(id) on delete cascade, incident_id uuid not null references incidents(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, evidence_revision timestamptz not null, reviewed_at timestamptz not null default now(), primary key(incident_id,user_id));
      create table if not exists change_proposals (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, incident_id uuid not null references incidents(id) on delete cascade, version integer not null, supersedes_id uuid references change_proposals(id), title text not null, change_text text not null, rollback_plan text not null, target jsonb not null default '{}', evidence_revision timestamptz not null, created_by text not null, created_at timestamptz not null default now(), unique(incident_id,version));
      create table if not exists validation_artifacts (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, incident_id uuid not null references incidents(id) on delete cascade, proposal_id uuid not null references change_proposals(id) on delete cascade, proposal_version integer not null, kind text not null, status text not null, summary text not null, provenance jsonb not null default '{}', evidence_revision timestamptz not null, created_by text not null, created_at timestamptz not null default now());
      create table if not exists proposal_reviews (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, incident_id uuid not null references incidents(id) on delete cascade, proposal_id uuid not null references change_proposals(id) on delete cascade, proposal_version integer not null, requested_by text not null, reviewed_by text, status text not null default 'pending', reason text not null default '', evidence_revision timestamptz not null, created_at timestamptz not null default now(), reviewed_at timestamptz);
      create table if not exists recovery_criteria (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, incident_id uuid not null references incidents(id) on delete cascade, version integer not null, kind text not null, name text not null, source text not null, query text not null, unit text not null, comparison text not null, target_value double precision not null, min_consecutive_windows integer not null, max_age_minutes integer not null, observation_minutes integer not null, delivery_identity jsonb, created_at timestamptz not null default now(), unique(incident_id,version));
      create table if not exists typed_measurements (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, incident_id uuid not null references incidents(id) on delete cascade, criterion_id uuid not null references recovery_criteria(id) on delete cascade, value double precision, unit text not null, source text not null, query text not null, window_started_at timestamptz not null, window_ended_at timestamptz not null, observed_at timestamptz not null, state text not null, note text not null default '', created_at timestamptz not null default now());
      create table if not exists incident_resolutions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, incident_id uuid not null references incidents(id) on delete cascade, actor text not null, reason text not null, recovery_evaluation jsonb not null, evidence_revision timestamptz not null, resolved_at timestamptz not null default now());
      create index if not exists investigation_checks_incident_idx on investigation_checks(incident_id,updated_at desc);
      create index if not exists validation_artifacts_incident_idx on validation_artifacts(incident_id,created_at desc);
      create index if not exists typed_measurements_incident_idx on typed_measurements(incident_id,observed_at desc);
      alter table investigation_checks enable row level security;
      alter table evidence_review_cursors enable row level security;
      alter table change_proposals enable row level security;
      alter table validation_artifacts enable row level security;
      alter table proposal_reviews enable row level security;
      alter table recovery_criteria enable row level security;
      alter table typed_measurements enable row level security;
      alter table incident_resolutions enable row level security;
    `);
  }
  private async org(userId:string, client:Pool | PoolClient = this.pool!) { const result=await client.query("select organization_id from organization_members where user_id=$1 order by created_at desc limit 1",[userId]); if(!result.rows[0])throw new Error("No workspace membership found."); return String(result.rows[0].organization_id); }
  private mapCheck(row:Record<string,unknown>):InvestigationCheck{return {id:String(row.id),incidentId:String(row.incident_id),templateId:String(row.template_id),title:String(row.title),question:String(row.question),method:String(row.method),expectedSignal:String(row.expected_signal),conditions:String(row.conditions),result:String(row.result??""),status:row.status as CheckStatus,assignee:String(row.assignee),evidenceIds:Array.isArray(row.evidence_ids)?row.evidence_ids.map(String):[],evidenceRevision:iso(row.evidence_revision),conclusionState:row.conclusion_state as InvestigationCheck["conclusionState"],createdAt:iso(row.created_at),updatedAt:iso(row.updated_at)};}
  private mapProposal(row:Record<string,unknown>):ChangeProposal{return {id:String(row.id),incidentId:String(row.incident_id),version:Number(row.version),supersedesId:row.supersedes_id?String(row.supersedes_id):null,title:String(row.title),change:String(row.change_text),rollbackPlan:String(row.rollback_plan),target:(row.target??{}) as Record<string,unknown>,evidenceRevision:iso(row.evidence_revision),createdBy:String(row.created_by),createdAt:iso(row.created_at)};}
  private mapValidation(row:Record<string,unknown>):ValidationArtifact{return {id:String(row.id),incidentId:String(row.incident_id),proposalId:String(row.proposal_id),proposalVersion:Number(row.proposal_version),kind:row.kind as ValidationKind,status:row.status as ValidationStatus,summary:String(row.summary),provenance:(row.provenance??{}) as Record<string,unknown>,evidenceRevision:iso(row.evidence_revision),createdBy:String(row.created_by),createdAt:iso(row.created_at)};}
  private mapReview(row:Record<string,unknown>):ProposalReview{return {id:String(row.id),incidentId:String(row.incident_id),proposalId:String(row.proposal_id),proposalVersion:Number(row.proposal_version),requestedBy:String(row.requested_by),reviewedBy:row.reviewed_by?String(row.reviewed_by):null,status:row.status as ProposalReview["status"],reason:String(row.reason??""),evidenceRevision:iso(row.evidence_revision),createdAt:iso(row.created_at),reviewedAt:row.reviewed_at?iso(row.reviewed_at):null};}
  private mapCriterion(row:Record<string,unknown>):RecoveryCriterion{return {id:String(row.id),incidentId:String(row.incident_id),version:Number(row.version),kind:row.kind as RecoveryKind,name:String(row.name),source:String(row.source),query:String(row.query),unit:String(row.unit),comparison:row.comparison as "lte"|"gte",targetValue:Number(row.target_value),minConsecutiveWindows:Number(row.min_consecutive_windows),maxAgeMinutes:Number(row.max_age_minutes),observationMinutes:Number(row.observation_minutes),deliveryIdentity:row.delivery_identity as Record<string,unknown>|null,createdAt:iso(row.created_at)};}
  private mapMeasurement(row:Record<string,unknown>):TypedMeasurement{return {id:String(row.id),incidentId:String(row.incident_id),criterionId:String(row.criterion_id),value:row.value===null?null:Number(row.value),unit:String(row.unit),source:String(row.source),query:String(row.query),windowStartedAt:iso(row.window_started_at),windowEndedAt:iso(row.window_ended_at),observedAt:iso(row.observed_at),state:row.state as TypedMeasurement["state"],note:String(row.note??""),createdAt:iso(row.created_at)};}
  private caseKind(incident:Incident):CaseworkSnapshot["caseKind"] { const active=incident.events.filter((item)=>item.evidenceState!=="excluded"); const ci=active.some((item)=>item.metadata?.ciOnly===true||item.metadata?.source==="github"); const runtime=active.some((item)=>item.metadata?.traceId||item.metadata?.metricType||item.metadata?.provider==="grafana"||item.kind==="recovery"); return runtime?"runtime":ci?"delivery":"uncertain"; }
  async snapshot(userId:string,incident:Incident):Promise<CaseworkSnapshot>{
    let checks:InvestigationCheck[],proposals:ChangeProposal[],validations:ValidationArtifact[],reviews:ProposalReview[],criteria:RecoveryCriterion[],measurements:TypedMeasurement[],reviewedRevision:string|null;
    if(!this.pool){checks=clone(this.memory.checks.filter(x=>x.incidentId===incident.id));proposals=clone(this.memory.proposals.filter(x=>x.incidentId===incident.id));validations=clone(this.memory.validations.filter(x=>x.incidentId===incident.id));reviews=clone(this.memory.reviews.filter(x=>x.incidentId===incident.id));criteria=clone(this.memory.criteria.filter(x=>x.incidentId===incident.id));measurements=clone(this.memory.measurements.filter(x=>x.incidentId===incident.id));reviewedRevision=this.memory.cursors.get(`${userId}:${incident.id}`)??null;}
    else {const org=await this.org(userId);const [a,b,c,g,d,e,f]=await Promise.all([this.pool.query("select * from investigation_checks where organization_id=$1 and incident_id=$2 order by updated_at desc",[org,incident.id]),this.pool.query("select * from change_proposals where organization_id=$1 and incident_id=$2 order by version desc",[org,incident.id]),this.pool.query("select * from validation_artifacts where organization_id=$1 and incident_id=$2 order by created_at desc",[org,incident.id]),this.pool.query("select * from proposal_reviews where organization_id=$1 and incident_id=$2 order by created_at desc",[org,incident.id]),this.pool.query("select * from recovery_criteria where organization_id=$1 and incident_id=$2 order by version desc",[org,incident.id]),this.pool.query("select * from typed_measurements where organization_id=$1 and incident_id=$2 order by observed_at desc",[org,incident.id]),this.pool.query("select evidence_revision from evidence_review_cursors where organization_id=$1 and incident_id=$2 and user_id=$3",[org,incident.id,userId])]);checks=a.rows.map((x)=>this.mapCheck(x));proposals=b.rows.map((x)=>this.mapProposal(x));validations=c.rows.map((x)=>this.mapValidation(x));reviews=g.rows.map((x)=>this.mapReview(x));criteria=d.rows.map((x)=>this.mapCriterion(x));measurements=e.rows.map((x)=>this.mapMeasurement(x));reviewedRevision=f.rows[0]?iso(f.rows[0].evidence_revision):null;}
    const currentRevision=incident.evidenceRevision??incident.updatedAt;const changed=Boolean(reviewedRevision&&reviewedRevision!==currentRevision);const affectedCheckIds=changed?checks.filter((x)=>x.evidenceRevision!==currentRevision).map((x)=>x.id):[];for(const check of checks)if(affectedCheckIds.includes(check.id))check.conclusionState="needs_recheck";
    const latestCriterion=criteria[0];const kind=latestCriterion?.kind??this.caseKind(incident);const recovery=kind==="delivery"?evaluateDeliveryRecovery(latestCriterion,validations):evaluateRuntimeRecovery(latestCriterion,measurements);
    return {caseKind:this.caseKind(incident),checks,proposals,validations,reviews,criteria,measurements,recovery,evidenceReview:{reviewedRevision,currentRevision,changed,affectedCheckIds}};
  }
  suggestions(incident:Incident){const missing=incident.events.length<2;return templates.map((item,index)=>({...item,applicable:index===1||index===3||(!missing&&index<3),blockedReason:missing&&index!==1&&index!==3?"More source evidence is required.":null}));}
  async acknowledge(userId:string,incident:Incident){const revision=incident.evidenceRevision??incident.updatedAt;if(!this.pool){this.memory.cursors.set(`${userId}:${incident.id}`,revision);return {evidenceRevision:revision,reviewedAt:new Date().toISOString()};}const org=await this.org(userId);const result=await this.pool.query("insert into evidence_review_cursors(organization_id,incident_id,user_id,evidence_revision) values($1,$2,$3,$4) on conflict(incident_id,user_id) do update set evidence_revision=excluded.evidence_revision,reviewed_at=now() returning *",[org,incident.id,userId,revision]);return {evidenceRevision:iso(result.rows[0].evidence_revision),reviewedAt:iso(result.rows[0].reviewed_at)};}
  async createCheck(userId:string,incident:Incident,actor:string,input:{templateId:string;title:string;question:string;method:string;expectedSignal:string;conditions:string;assignee:string;evidenceIds:string[]}){const now=new Date().toISOString();const value:InvestigationCheck={id:randomUUID(),incidentId:incident.id,...input,result:"",status:"planned",evidenceRevision:incident.evidenceRevision??incident.updatedAt,conclusionState:"current",createdAt:now,updatedAt:now};if(!this.pool){this.memory.checks.unshift(value);return clone(value);}const org=await this.org(userId);const r=await this.pool.query("insert into investigation_checks(id,organization_id,incident_id,template_id,title,question,method,expected_signal,conditions,assignee,evidence_ids,evidence_revision,status) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,'planned') returning *",[value.id,org,incident.id,input.templateId,input.title,input.question,input.method,input.expectedSignal,input.conditions,input.assignee,input.evidenceIds,value.evidenceRevision]);return this.mapCheck(r.rows[0]);}
  async updateCheck(userId:string,id:string,input:{status:CheckStatus;result:string;evidenceIds:string[]},incident:Incident){if(!this.pool){const item=this.memory.checks.find(x=>x.id===id);if(!item)throw new Error("Investigation check not found.");Object.assign(item,input,{evidenceRevision:incident.evidenceRevision??incident.updatedAt,conclusionState:"current",updatedAt:new Date().toISOString()});return clone(item);}const org=await this.org(userId);const r=await this.pool.query("update investigation_checks set status=$3,result=$4,evidence_ids=$5,evidence_revision=$6,conclusion_state='current',updated_at=now() where id=$1 and organization_id=$2 returning *",[id,org,input.status,input.result,input.evidenceIds,incident.evidenceRevision??incident.updatedAt]);if(!r.rows[0])throw new Error("Investigation check not found.");return this.mapCheck(r.rows[0]);}
  async createProposal(userId:string,incident:Incident,actor:string,input:{title:string;change:string;rollbackPlan:string;target:Record<string,unknown>}){const previous=(await this.snapshot(userId,incident)).proposals[0];const value:ChangeProposal={id:randomUUID(),incidentId:incident.id,version:(previous?.version??0)+1,supersedesId:previous?.id??null,...input,evidenceRevision:incident.evidenceRevision??incident.updatedAt,createdBy:actor,createdAt:new Date().toISOString()};if(!this.pool){this.memory.proposals.unshift(value);return clone(value);}const org=await this.org(userId);const r=await this.pool.query("insert into change_proposals(id,organization_id,incident_id,version,supersedes_id,title,change_text,rollback_plan,target,evidence_revision,created_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) returning *",[value.id,org,incident.id,value.version,value.supersedesId,value.title,value.change,value.rollbackPlan,value.target,value.evidenceRevision,actor]);return this.mapProposal(r.rows[0]);}
  async addValidation(userId:string,incident:Incident,proposal:ChangeProposal,actor:string,input:{kind:ValidationKind;status:ValidationStatus;summary:string;provenance:Record<string,unknown>}){if(proposal.evidenceRevision!==(incident.evidenceRevision??incident.updatedAt))throw new Error("Evidence changed after this proposal version. Create a new proposal version before validating it.");const value:ValidationArtifact={id:randomUUID(),incidentId:incident.id,proposalId:proposal.id,proposalVersion:proposal.version,...input,evidenceRevision:proposal.evidenceRevision,createdBy:actor,createdAt:new Date().toISOString()};if(!this.pool){this.memory.validations.unshift(value);return clone(value);}const org=await this.org(userId);const r=await this.pool.query("insert into validation_artifacts(id,organization_id,incident_id,proposal_id,proposal_version,kind,status,summary,provenance,evidence_revision,created_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) returning *",[value.id,org,incident.id,proposal.id,proposal.version,input.kind,input.status,input.summary,input.provenance,value.evidenceRevision,actor]);return this.mapValidation(r.rows[0]);}
  async requestReview(userId:string,incident:Incident,proposal:ChangeProposal,actor:string){const snapshot=await this.snapshot(userId,incident);if(proposal.evidenceRevision!==(incident.evidenceRevision??incident.updatedAt))throw new Error("Evidence changed. Create a new proposal version before requesting approval.");if(!snapshot.validations.some((item)=>item.proposalId===proposal.id&&item.status==="passed"))throw new Error("Attach a passing validation artifact for this exact proposal version before requesting approval.");if(snapshot.reviews.some((item)=>item.proposalId===proposal.id&&item.status==="pending"))throw new Error("This proposal version already has a pending review.");const value:ProposalReview={id:randomUUID(),incidentId:incident.id,proposalId:proposal.id,proposalVersion:proposal.version,requestedBy:actor,reviewedBy:null,status:"pending",reason:"",evidenceRevision:proposal.evidenceRevision,createdAt:new Date().toISOString(),reviewedAt:null};if(!this.pool){this.memory.reviews.unshift(value);return clone(value);}const org=await this.org(userId);const r=await this.pool.query("insert into proposal_reviews(id,organization_id,incident_id,proposal_id,proposal_version,requested_by,evidence_revision) values($1,$2,$3,$4,$5,$6,$7) returning *",[value.id,org,incident.id,proposal.id,proposal.version,actor,proposal.evidenceRevision]);return this.mapReview(r.rows[0]);}
  async reviewProposal(userId:string,incident:Incident,reviewId:string,actor:string,role:WorkspaceRole,input:{status:"approved"|"rejected";reason:string}){const snapshot=await this.snapshot(userId,incident);const review=snapshot.reviews.find((item)=>item.id===reviewId);if(!review||review.status!=="pending")throw new Error("Pending proposal review not found.");if(role!=="admin")throw new Error("Only a workspace administrator can approve or reject an exact production change.");if(review.requestedBy.trim().toLowerCase()===actor.trim().toLowerCase())throw new Error("The requester cannot review their own change. Use a different administrator identity.");if(review.evidenceRevision!==(incident.evidenceRevision??incident.updatedAt))throw new Error("Evidence changed after review was requested. Save and validate a new proposal version.");if(!this.pool){Object.assign(review,{status:input.status,reason:input.reason,reviewedBy:actor,reviewedAt:new Date().toISOString()});const stored=this.memory.reviews.find((item)=>item.id===reviewId)!;Object.assign(stored,review);return clone(review);}const org=await this.org(userId);const r=await this.pool.query("update proposal_reviews set status=$3,reason=$4,reviewed_by=$5,reviewed_at=now() where id=$1 and organization_id=$2 and status='pending' returning *",[reviewId,org,input.status,input.reason,actor]);if(!r.rows[0])throw new Error("Pending proposal review not found.");return this.mapReview(r.rows[0]);}
  async createCriterion(userId:string,incident:Incident,input:Omit<RecoveryCriterion,"id"|"incidentId"|"version"|"createdAt">){const previous=(await this.snapshot(userId,incident)).criteria[0];const value:RecoveryCriterion={id:randomUUID(),incidentId:incident.id,version:(previous?.version??0)+1,...input,createdAt:new Date().toISOString()};if(!this.pool){this.memory.criteria.unshift(value);return clone(value);}const org=await this.org(userId);const r=await this.pool.query("insert into recovery_criteria(id,organization_id,incident_id,version,kind,name,source,query,unit,comparison,target_value,min_consecutive_windows,max_age_minutes,observation_minutes,delivery_identity) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) returning *",[value.id,org,incident.id,value.version,value.kind,value.name,value.source,value.query,value.unit,value.comparison,value.targetValue,value.minConsecutiveWindows,value.maxAgeMinutes,value.observationMinutes,value.deliveryIdentity]);return this.mapCriterion(r.rows[0]);}
  async addMeasurement(userId:string,incident:Incident,input:Omit<TypedMeasurement,"id"|"incidentId"|"createdAt">){if(Date.parse(input.windowEndedAt)<=Date.parse(input.windowStartedAt))throw new Error("Measurement window must end after it starts.");const value:TypedMeasurement={id:randomUUID(),incidentId:incident.id,...input,createdAt:new Date().toISOString()};if(!this.pool){this.memory.measurements.unshift(value);return clone(value);}const org=await this.org(userId);const r=await this.pool.query("insert into typed_measurements(id,organization_id,incident_id,criterion_id,value,unit,source,query,window_started_at,window_ended_at,observed_at,state,note) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) returning *",[value.id,org,incident.id,input.criterionId,input.value,input.unit,input.source,input.query,input.windowStartedAt,input.windowEndedAt,input.observedAt,input.state,input.note]);return this.mapMeasurement(r.rows[0]);}
  async transition(userId:string,incidentId:string,actor:string,role:WorkspaceRole,input:{action:"start_monitoring"|"resolve"|"reopen";reason:string;expectedEvidenceRevision:string}){
    if(!this.pool){const incident=await repository.getIncident(userId,incidentId);if(!incident)throw new Error("Incident not found.");if((incident.evidenceRevision??incident.updatedAt)!==input.expectedEvidenceRevision)throw new Error("Evidence changed. Review the latest evidence before changing lifecycle state.");const snap=await this.snapshot(userId,incident);if(input.action==="resolve"&&(incident.status!=="monitoring"||snap.recovery.state!=="verified"))throw new Error(incident.status!=="monitoring"?"Move the incident to Monitoring before resolving it.":snap.recovery.reason);if(input.action==="resolve"&&snap.proposals[0]&&!snap.reviews.some((item)=>item.proposalId===snap.proposals[0]!.id&&item.status==="approved"))throw new Error("The latest proposed production change requires independent approval before resolution.");const status=input.action==="resolve"?"resolved":input.action==="start_monitoring"?"monitoring":"investigating";return repository.updateIncident(userId,incidentId,{status,resolvedAt:status==="resolved"?new Date().toISOString():null});}
    const client=await this.pool.connect();try{await client.query("begin");const org=await this.org(userId,client);const locked=await client.query("select * from incidents where id=$1 and organization_id=$2 for update",[incidentId,org]);if(!locked.rows[0])throw new Error("Incident not found.");const row=locked.rows[0];const current=iso(row.evidence_revision??row.updated_at);if(current!==input.expectedEvidenceRevision)throw new Error("Evidence changed. Review the latest evidence before changing lifecycle state.");const incident=await repository.getIncident(userId,incidentId);if(!incident)throw new Error("Incident not found.");const snap=await this.snapshot(userId,incident);if(input.action==="resolve"&&String(row.status)!=="monitoring")throw new Error("Move the incident to Monitoring before resolving it.");if(input.action==="resolve"&&snap.recovery.state!=="verified")throw new Error(snap.recovery.reason);if(input.action==="resolve"&&snap.proposals[0]&&!snap.reviews.some((item)=>item.proposalId===snap.proposals[0]!.id&&item.status==="approved"))throw new Error("The latest proposed production change requires independent approval before resolution.");if(input.action==="resolve"&&role!=="admin"&&role!=="responder")throw new Error("Your role cannot resolve incidents.");const status=input.action==="resolve"?"resolved":input.action==="start_monitoring"?"monitoring":"investigating";await client.query("update incidents set status=$3,resolved_at=case when $3='resolved' then now() else null end,updated_at=now() where id=$1 and organization_id=$2",[incidentId,org,status]);if(input.action==="resolve")await client.query("insert into incident_resolutions(organization_id,incident_id,actor,reason,recovery_evaluation,evidence_revision) values($1,$2,$3,$4,$5,$6)",[org,incidentId,actor,input.reason,snap.recovery,current]);await client.query("insert into workspace_audit_log(organization_id,actor,action,target_type,target_id,detail) values($1,$2,$3,'incident',$4,$5)",[org,actor,input.action==="resolve"?"resolved incident after fresh recovery verification":input.action==="start_monitoring"?"started recovery monitoring":"reopened incident",incidentId,{reason:input.reason,recovery:snap.recovery,evidenceRevision:current}]);await client.query("commit");return await repository.getIncident(userId,incidentId);}catch(error){await client.query("rollback");throw error;}finally{client.release();}
  }
}

export const caseworkService = new CaseworkService();
