import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowRight, BellRing, CheckCircle2, CircleDot, Clock3, DatabaseZap, Plus, RadioTower, TriangleAlert, UserRound } from "lucide-react";
import { useState } from "react";
import { Link } from "react-router-dom";
import { IncidentEditor, type IncidentDraft } from "../components/IncidentEditor";
import { DashboardSkeleton } from "../components/Skeleton";
import { SeverityMark, StatusMark } from "../components/StatusMark";
import { api } from "../lib/api";
import { cn, formatRelative } from "../lib/utils";
import type { DashboardData, Incident } from "../types";
import { useAuth } from "../providers/AuthProvider";
import { useOwnerName } from "../lib/useOwnerName";

function sourceState(provider: string, receivedAt?: string | null) {
  if (!receivedAt) return { label:"Awaiting first real receipt", tone:"text-warning", action:"Send one event from the source" };
  const age = Date.now() - Date.parse(receivedAt);
  const expected = provider === "otel" ? 15 * 60_000 : provider === "github" ? 7 * 24 * 60 * 60_000 : 3 * 60 * 60_000;
  return age <= expected ? { label:"Receiving as expected", tone:"text-success", action:"View delivery path" } : { label:"Outside expected cadence", tone:"text-danger", action:"Inspect last delivery" };
}

export function DashboardPage() {
  const [editorOpen, setEditorOpen] = useState(false);
  const queryClient = useQueryClient();
  const { user } = useAuth();
  const ownerName = useOwnerName();
  const dashboard = useQuery({ queryKey:["dashboard"], queryFn:api.dashboard });
  const sources = useQuery({ queryKey:["integrations"], queryFn:api.integrations });
  const notifications = useQuery({ queryKey:["notifications"], queryFn:api.notifications });
  const queue = useQuery({ queryKey:["ingestion-queue"], queryFn:api.queue });
  const alertChannels = useQuery({ queryKey:["alert-channels"], queryFn:api.alertChannels });
  const createIncident = useMutation({
    mutationFn:async(draft:IncidentDraft) => {
      const created=await api.createIncident(draft);
      if(draft.intakeLink) await api.createEvent(created.id,{timestamp:draft.startedAt,service:draft.service,kind:"alert",title:"Imported alert or trace link",detail:`Investigation started from ${draft.intakeLink}. Verify the source and attach the observed symptom.`,impactScore:65,provenance:"manual",evidenceState:"active",metadata:{sourceUrl:draft.intakeLink,intake:true}});
      return created;
    },
    onMutate:async(draft) => { await queryClient.cancelQueries({ queryKey:["dashboard"] }); const previous=queryClient.getQueryData<DashboardData>(["dashboard"]); const optimistic:Incident={...draft,id:`optimistic-${Date.now()}`,code:"ROP-NEW",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),evidenceRevision:new Date().toISOString(),events:[]}; queryClient.setQueryData<DashboardData>(["dashboard"],(current)=>current?{...current,incidents:[optimistic,...current.incidents]}:current); return {previous}; }, onError:(_error,_draft,context)=>queryClient.setQueryData(["dashboard"],context?.previous), onSuccess:()=>setEditorOpen(false), onSettled:()=>{void queryClient.invalidateQueries({queryKey:["dashboard"]});void queryClient.invalidateQueries({queryKey:["incidents"]});}
  });
  if (dashboard.isLoading) return <DashboardSkeleton />;
  if (dashboard.error || !dashboard.data) return <div className="surface-lined mx-auto max-w-xl p-6 text-center"><TriangleAlert className="mx-auto h-7 w-7 text-danger" /><h1 className="mt-4 font-heading text-2xl font-semibold">Investigations are unavailable</h1><p className="mt-2 text-sm text-muted">{dashboard.error instanceof Error ? dashboard.error.message : "The workspace could not be loaded."}</p><button className="control-primary mt-5" onClick={() => void dashboard.refetch()}>Retry</button></div>;
  const data=dashboard.data;
  const active=data.incidents.filter((item)=>item.status!=="resolved");
  const realReceipt=sources.data?.some((source)=>source.deliveries.some((delivery)=>!delivery.externalId.includes("self-test")));
  const deadLetters=queue.data?.filter((job)=>job.status==="dead_letter" || job.status==="retrying") ?? [];
  return <div className="space-y-6">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="measurement-number text-xs uppercase tracking-[.14em] text-muted">Responder workspace</p><h1 className="mt-2 font-heading text-3xl font-semibold tracking-[-.03em] sm:text-4xl">Investigations</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted">Find what needs attention, what evidence is fresh, and the next useful action—without rebuilding your observability stack.</p></div><div className="flex gap-2"><Link to="/integrations" className="control-secondary inline-flex items-center gap-2"><RadioTower className="h-4 w-4" />Connect source</Link><button className="control-primary inline-flex items-center gap-2" onClick={()=>setEditorOpen(true)}><Plus className="h-4 w-4" />Quick intake</button></div></header>
    {realReceipt && alertChannels.data && !alertChannels.data.length && <Link to="/workspace?tab=alerts" className="surface-lined flex items-center gap-3 p-4 text-sm transition-colors hover:bg-elevated"><BellRing className="h-5 w-5 shrink-0 text-warning" /><span className="min-w-0 flex-1"><strong>Nobody is notified when an incident opens.</strong> <span className="text-muted">Add a free email or phone-push alert so automatic incidents reach you.</span></span><ArrowRight className="h-4 w-4 shrink-0 text-muted" /></Link>}

    {!realReceipt && <section className="surface-lined grid gap-5 p-5 sm:p-6 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="flex items-center gap-2"><DatabaseZap className="h-5 w-5 text-info" /><h2 className="font-heading text-xl font-semibold">Get to the first real investigation</h2></div><p className="mt-2 max-w-3xl text-sm leading-6 text-muted">Choose GitHub, OpenTelemetry, or a generic webhook; send one real event; then open the investigation it creates. Connector self-tests stay labeled as synthetic and never count as source activation.</p></div><Link to="/integrations" className="control-primary inline-flex items-center gap-2">Set up a source <ArrowRight className="h-4 w-4" /></Link></section>}

    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div className="surface-lined p-4"><p className="text-xs font-semibold uppercase tracking-[.12em] text-muted">Active</p><p className="measurement-number mt-2 text-2xl font-semibold">{active.length}</p><p className="mt-1 text-xs text-muted">investigations not resolved</p></div><div className="surface-lined p-4"><p className="text-xs font-semibold uppercase tracking-[.12em] text-muted">My ownership</p><p className="measurement-number mt-2 text-2xl font-semibold">{active.filter((item)=>item.owner===user?.email || item.owner===user?.name).length}</p><p className="mt-1 text-xs text-muted">assigned to you</p></div><div className="surface-lined p-4"><p className="text-xs font-semibold uppercase tracking-[.12em] text-muted">Actions waiting</p><p className="measurement-number mt-2 text-2xl font-semibold">{notifications.data?.length ?? "—"}</p><p className="mt-1 text-xs text-muted">tests, reviews, source failures</p></div><div className="surface-lined p-4"><p className="text-xs font-semibold uppercase tracking-[.12em] text-muted">Intake failures</p><p className={cn("measurement-number mt-2 text-2xl font-semibold",deadLetters.length?"text-danger":"text-success")}>{deadLetters.length}</p><p className="mt-1 text-xs text-muted">retrying or dead-lettered</p></div></div>

    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.35fr)_minmax(340px,.65fr)]"><section className="surface-lined overflow-hidden" aria-labelledby="active-title"><div className="flex items-center justify-between px-5 py-5 sm:px-6"><div><h2 id="active-title" className="section-title">Active investigations</h2><p className="mt-1 text-sm text-muted">Impact, environment, owner, freshness, and next action</p></div><Link to="/incidents" className="text-sm font-semibold underline decoration-line underline-offset-4">All views</Link></div><div className="divide-y divide-line border-t border-line">{active.slice(0,8).map((item)=>{const latest=item.events.at(-1);const unowned=!item.owner||item.owner==="Automation";const next=item.status==="monitoring"?"Confirm recovery, then resolve":unowned?"Assign an owner":(item.eventCount ?? item.events.length)<2?"Add more evidence":"Run the next check";return <Link key={item.id} to={`/incidents/${item.id}?area=${item.status==="monitoring"?"validate":"investigate"}#investigation-workspace`} className="group block px-5 py-4 transition-colors hover:bg-elevated sm:px-6"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="measurement-number text-xs text-muted">{item.code}</span><SeverityMark value={item.severity}/><StatusMark value={item.status}/>{item.environment && item.environment !== "unknown" && <span className="rounded-full bg-elevated px-2 py-.5 text-xs font-semibold">{item.environment}</span>}</div><p className="mt-2 truncate text-sm font-semibold">{item.title}</p><p className="mt-1 line-clamp-1 text-xs text-muted">{item.customerImpact || "Customer impact unknown"}</p></div><ArrowRight className="mt-2 h-4 w-4 text-faint transition-transform group-hover:translate-x-1" /></div><div className="mt-3 grid gap-2 text-xs text-muted sm:grid-cols-3"><span className="inline-flex items-center gap-1.5"><UserRound className="h-3.5 w-3.5" />{ownerName(item.owner)}</span><span className="inline-flex items-center gap-1.5"><Clock3 className="h-3.5 w-3.5" />{latest?`evidence ${formatRelative(latest.timestamp)}`:"no evidence"}</span><span className="font-semibold text-info">{next}</span></div></Link>;})}{!active.length&&<div className="px-6 py-14 text-center"><CheckCircle2 className="mx-auto h-7 w-7 text-success"/><p className="mt-3 font-semibold">No active investigations</p><p className="mt-1 text-sm text-muted">Source deliveries remain visible even when there is no incident.</p></div>}</div></section>
      <div className="space-y-6"><section className="surface-lined overflow-hidden"><div className="px-5 py-5"><h2 className="section-title">Actions needing attention</h2><p className="mt-1 text-sm text-muted">Exact tasks, not generic activity</p></div><div className="divide-y divide-line border-t border-line">{notifications.data?.slice(0,6).map((item)=><Link key={item.id} to={item.href} className="block px-5 py-4 hover:bg-elevated"><div className="flex items-center justify-between gap-2"><p className="text-sm font-semibold">{item.title}</p><span className="measurement-number text-xs uppercase text-muted">{item.kind}</span></div><p className="mt-1 text-xs leading-5 text-muted">{item.detail}</p></Link>)}{notifications.data&&!notifications.data.length&&<p className="px-5 py-10 text-center text-sm text-muted">No assigned actions are waiting.</p>}</div></section><section className="surface-lined overflow-hidden"><div className="flex items-center justify-between px-5 py-5"><div><h2 className="section-title">Source freshness</h2><p className="mt-1 text-sm text-muted">Cadence-aware receipt health</p></div><Link to="/integrations" className="text-xs font-semibold text-info">Open Sources</Link></div><div className="divide-y divide-line border-t border-line">{sources.data?.map((source)=>{const state=sourceState(source.provider,source.lastDeliveryAt);return <Link key={source.id} to={`/integrations?source=${source.id}`} className="block px-5 py-4 hover:bg-elevated"><div className="flex items-center gap-2"><CircleDot className={cn("h-4 w-4",state.tone)}/><p className="text-sm font-semibold">{source.name}</p><span className="measurement-number ml-auto text-xs uppercase text-muted">{source.provider}</span></div><p className={cn("mt-1 text-xs font-semibold",state.tone)}>{state.label}</p><p className="mt-1 text-xs text-muted">{state.action}</p></Link>;})}{sources.data&&!sources.data.length&&<p className="px-5 py-10 text-center text-sm text-muted">No real source configured.</p>}</div></section></div>
    </div>
    <IncidentEditor open={editorOpen} saving={createIncident.isPending} error={createIncident.error instanceof Error?createIncident.error.message:undefined} onClose={()=>setEditorOpen(false)} onSave={(draft)=>createIncident.mutate(draft)} />
  </div>;
}
