import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { motion } from "framer-motion";
import { ArrowLeft, CheckCircle2, Edit3, LoaderCircle, Plus, RotateCcw, Trash2, TriangleAlert, UserRound, Wifi } from "lucide-react";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { Link, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { CausalTrace } from "../components/CausalTrace";
import { EvidenceLedger } from "../components/EvidenceLedger";
import { IncidentEditor, type IncidentDraft } from "../components/IncidentEditor";
import { ResponseConsole } from "../components/ResponseConsole";
import { DebuggingInsights } from "../components/DebuggingInsights";
import { Skeleton } from "../components/Skeleton";
import { SeverityMark, StatusMark } from "../components/StatusMark";
import { api } from "../lib/api";
import { usePersistentDraft } from "../lib/usePersistentDraft";
import { cn, durationBetween, formatRelative, toLocalDateTimeInput } from "../lib/utils";
import type { TimelineWindow } from "../lib/timeline";
import { useTimeZone } from "../providers/TimeZoneProvider";
import type { EventKind, Incident, IncidentDiagnosis, IncidentEvent, IncidentStatus } from "../types";

type EventDraft = Omit<IncidentEvent, "id" | "incidentId">;
type EditorDraft = { timestamp: string; service: string; kind: EventKind; title: string; detail: string };

function EventEditor({ incidentId, event, saving, error, onCancel, onSave }: { incidentId: string; event?: IncidentEvent | null; saving: boolean; error?: string; onCancel(): void; onSave(value: EventDraft): void }) {
  const initial: EditorDraft = { timestamp: toLocalDateTimeInput(event?.timestamp ?? new Date().toISOString()), service: event?.service ?? "", kind: event?.kind ?? "metric", title: event?.title ?? "", detail: event?.detail ?? "" };
  const draft = usePersistentDraft(`replayops:${incidentId}:evidence:${event?.id ?? "new"}`, initial);
  useEffect(() => { if (event) draft.setValue({ timestamp: toLocalDateTimeInput(event.timestamp), service: event.service, kind: event.kind, title: event.title, detail: event.detail }); }, [event?.id]);
  const set = (key: keyof EditorDraft, value: string) => draft.setValue((current) => ({ ...current, [key]: value }));
  function submit(formEvent: FormEvent) {
    formEvent.preventDefault();
    const inferredImpact: Record<EventKind, number> = { alert: 75, deploy: 35, dependency: 55, metric: 50, action: 25, recovery: 15 };
    onSave({ timestamp: new Date(draft.value.timestamp).toISOString(), service: draft.value.service.trim(), kind: draft.value.kind, title: draft.value.title.trim(), detail: draft.value.detail.trim(), impactScore: event?.impactScore ?? inferredImpact[draft.value.kind], evidenceState: event?.evidenceState ?? "active", provenance: event?.provenance ?? "manual", correctionReason: event ? "Corrected by responder; previous values remain in the audit trail." : null, correctedFromId: event?.id ?? null, metadata: event?.metadata ?? {} });
  }
  return <motion.form className="surface-lined p-5 sm:p-6" initial={{ opacity:.5, height:0 }} animate={{ opacity:1, height:"auto" }} onSubmit={submit}><div className="flex items-start justify-between gap-4"><div><h2 className="section-title">{event ? "Correct evidence" : "Add an observation"}</h2><p className="mt-1 text-sm text-muted">Record what was observed. Triage priority is inferred from type; it is not a measured customer-impact score.</p></div><button type="button" className="control-quiet !min-h-9" onClick={onCancel}>Cancel</button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Timestamp<input type="datetime-local" className="field mt-2" value={draft.value.timestamp} onChange={(event) => set("timestamp", event.target.value)} required /></label><label className="text-sm font-semibold">Service<input className="field mt-2" value={draft.value.service} onChange={(event) => set("service", event.target.value)} required placeholder="inventory-api" /></label><label className="text-sm font-semibold">Observation type<select className="field mt-2" value={draft.value.kind} onChange={(event) => set("kind", event.target.value)}><option value="alert">Alert</option><option value="deploy">Deployment / change</option><option value="dependency">Dependency</option><option value="metric">Metric / trace / log</option><option value="action">Responder action</option><option value="recovery">Recovery signal</option></select></label><div className="rounded-control bg-elevated p-3 text-xs leading-5 text-muted">{event ? "Saving creates an audited correction to this evidence revision." : "Manual observations are labeled separately from ingested telemetry."}</div><label className="text-sm font-semibold sm:col-span-2">Title<input className="field mt-2" value={draft.value.title} onChange={(event) => set("title", event.target.value)} required minLength={3} /></label><label className="text-sm font-semibold sm:col-span-2">Observed detail<textarea className="field mt-2 min-h-28 resize-y py-3" value={draft.value.detail} onChange={(event) => set("detail", event.target.value)} required minLength={8} /></label></div><p className="mt-3 text-xs text-muted">{draft.savedAt ? `Draft saved ${formatRelative(draft.savedAt)}` : "Draft autosaves locally."}</p>{error && <p role="alert" className="mt-4 rounded-control bg-danger/10 p-3 text-sm text-danger">{error}</p>}<div className="mt-5 flex justify-end"><button type="submit" className="control-primary min-w-36" disabled={saving}>{saving ? <span className="inline-flex items-center gap-2"><LoaderCircle className="h-4 w-4 animate-spin" />Saving</span> : event ? "Save correction" : "Add observation"}</button></div></motion.form>;
}

export function IncidentWorkbenchPage() {
  const { id = "" } = useParams();
  const navigate = useNavigate();
  const [params, setParams] = useSearchParams();
  const queryClient = useQueryClient();
  const { mode, setMode, zoneLabel, formatClock, formatDateTime } = useTimeZone();
  const [editingIncident, setEditingIncident] = useState(false);
  const [editingEvent, setEditingEvent] = useState<IncidentEvent | null | undefined>(undefined);
  const [timelineWindow, setTimelineWindow] = useState<TimelineWindow | null>(null);
  const [evidenceChange, setEvidenceChange] = useState("");
  const [movingEvent, setMovingEvent] = useState<IncidentEvent | null>(null);
  const [targetIncidentId, setTargetIncidentId] = useState("");
  const [lastMove,setLastMove]=useState<{event:IncidentEvent;from:string;to:string}|null>(null);
  const previousVersion = useRef<string | undefined>(undefined);
  const incident = useQuery({ queryKey: ["incident", id], queryFn: () => api.incident(id), enabled:Boolean(id), refetchInterval:10_000, refetchIntervalInBackground:true });
  const diagnosis = useQuery({ queryKey: ["diagnosis", id, incident.data?.evidenceRevision, incident.data?.status], queryFn: () => api.diagnosis(id), enabled:Boolean(incident.data) });
  const incidentOptions = useQuery({ queryKey: ["incidents"], queryFn: api.incidents });
  const members=useQuery({queryKey:["team-members"],queryFn:api.teamMembers});
  const selectedEventId = params.get("event");
  useEffect(() => {
    if (!incident.data) return;
    const revision = incident.data.evidenceRevision ?? incident.data.updatedAt;
    if (previousVersion.current && previousVersion.current !== revision) setEvidenceChange(`New evidence arrived at ${formatDateTime(revision)}. Explanations and candidate validity were recalculated.`);
    previousVersion.current = revision;
  }, [incident.data?.evidenceRevision, incident.data?.updatedAt]);

  const invalidateIncident = () => { void queryClient.invalidateQueries({ queryKey:["incident", id] }); void queryClient.invalidateQueries({ queryKey:["diagnosis", id] }); void queryClient.invalidateQueries({ queryKey:["dashboard"] }); void queryClient.invalidateQueries({ queryKey:["incidents"] }); };
  const updateIncident = useMutation({ mutationFn:(draft: IncidentDraft) => api.updateIncident(id, draft), onSuccess:(value) => { queryClient.setQueryData(["incident", id], value); setEditingIncident(false); }, onSettled:invalidateIncident });
  const lifecycle = useMutation({ mutationFn:(action:"start_monitoring"|"reopen") => { const current=incident.data;if(!current)throw new Error("Incident is not loaded.");return api.transitionIncident(id,{action,reason:action==="start_monitoring"?"Responder started a bounded recovery observation window.":"Responder reopened the incident after a regression or new evidence.",expectedEvidenceRevision:current.evidenceRevision??current.updatedAt}); }, onSuccess:(value) => queryClient.setQueryData(["incident", id], value), onSettled:invalidateIncident });
  const assign=useMutation({mutationFn:(owner:string)=>api.updateIncident(id,{owner}),onSuccess:(next)=>queryClient.setQueryData(["incident",id],next),onSettled:invalidateIncident});
  const deleteIncident = useMutation({ mutationFn:() => api.deleteIncident(id), onSuccess:() => { void queryClient.invalidateQueries({ queryKey:["incidents"] }); navigate("/incidents"); } });
  const saveEvent = useMutation({ mutationFn:(draft: EventDraft) => editingEvent ? api.updateEvent(id, editingEvent.id, draft) : api.createEvent(id, draft), onSuccess:() => setEditingEvent(undefined), onSettled:invalidateIncident });
  const updateEvidenceState = useMutation({ mutationFn:({ event, state }:{ event: IncidentEvent; state:"active"|"excluded" }) => api.updateEvent(id, event.id, { evidenceState:state, correctionReason:state === "excluded" ? "Excluded from diagnosis by responder; retained for provenance and undo." : "Restored to active evidence by responder." }), onSettled:invalidateIncident });
  const moveEvent = useMutation({ mutationFn:() => { if (!movingEvent || !targetIncidentId) throw new Error("Choose a target incident."); return api.moveEvent(id, movingEvent.id, targetIncidentId); }, onSuccess:(event) => { void api.recordProductOutcome("grouping_corrected",{incidentId:id,eventId:event.id});setLastMove({event,from:id,to:targetIncidentId});setMovingEvent(null); setTargetIncidentId(""); invalidateIncident(); } });
  const undoMove=useMutation({mutationFn:()=>{if(!lastMove)throw new Error("No grouping correction to undo.");return api.moveEvent(lastMove.to,lastMove.event.id,lastMove.from);},onSuccess:()=>{setLastMove(null);invalidateIncident();}});

  if (incident.isLoading) return <div className="space-y-5"><Skeleton className="h-8 w-40" /><Skeleton className="h-36 w-full rounded-panel" /><Skeleton className="h-[520px] w-full rounded-panel" /></div>;
  if (incident.error || !incident.data) return <div className="surface-lined mx-auto max-w-xl p-6 text-center"><TriangleAlert className="mx-auto h-7 w-7 text-danger" /><h1 className="mt-3 font-heading text-2xl font-semibold">Investigation unavailable</h1><p className="mt-2 text-sm text-muted">{incident.error instanceof Error ? incident.error.message : "This record may have been removed."}</p><Link to="/incidents" className="control-primary mt-5 inline-flex items-center gap-2"><ArrowLeft className="h-4 w-4" />Return to investigations</Link></div>;

  const value = incident.data;
  const diagnostic = diagnosis.data as IncidentDiagnosis | undefined;
  const selectEvent = (eventId: string, revealInspector = false) => { const next = new URLSearchParams(params); next.set("event", eventId); setParams(next, { replace:true }); if (revealInspector) window.setTimeout(() => document.getElementById("evidence-selected")?.scrollIntoView({ behavior:"smooth", block:"center" }), 80); };
  const sectionTarget = (anchor:string, area?:"investigate"|"validate"|"handoff") => { const next = new URLSearchParams(params); if (area) next.set("area",area); return { search:next.toString(), hash:`#${anchor}` }; };
  const sectionLinks = [
    { label:"Overview", anchor:"investigation-overview" },
    { label:"Timeline", anchor:"event-timeline" },
    { label:"Evidence", anchor:"evidence" },
    { label:"Debugging", anchor:"debugging-insights" },
    { label:"Investigate", anchor:"investigation-workspace", area:"investigate" as const },
    { label:"Fix & verify", anchor:"investigation-workspace", area:"validate" as const },
    { label:"Activity & handoff", anchor:"investigation-workspace", area:"handoff" as const }
  ];

  return <div className="space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><Link to="/incidents" className="inline-flex items-center gap-2 text-sm font-semibold text-muted hover:text-ink"><ArrowLeft className="h-4 w-4" />Investigations</Link><div className="flex items-center gap-2"><span className="inline-flex items-center gap-2 text-xs text-muted"><Wifi className={cn("h-3.5 w-3.5", incident.fetchStatus === "fetching" ? "animate-pulse text-info" : "text-success")} />{incident.fetchStatus === "fetching" ? "Checking for evidence" : `Updated ${formatRelative(new Date(incident.dataUpdatedAt).toISOString())}`}</span><div className="flex rounded-control bg-rail p-1"><button className={cn("rounded px-2 py-1 text-xs font-semibold", mode === "local" && "bg-panel")} onClick={() => setMode("local")}>Local</button><button className={cn("rounded px-2 py-1 text-xs font-semibold", mode === "utc" && "bg-panel")} onClick={() => setMode("utc")}>UTC</button></div></div></div>
    {evidenceChange && <div className="rounded-control bg-info/10 px-4 py-3 text-sm text-info" role="status">{evidenceChange}<button className="ml-3 font-semibold underline" onClick={() => setEvidenceChange("")}>Dismiss</button></div>}
    {lastMove&&<div className="flex flex-wrap items-center gap-3 rounded-control bg-success/10 px-4 py-3 text-sm text-success" role="status"><CheckCircle2 className="h-4 w-4"/>Evidence moved with provenance preserved.<button className="font-semibold underline" onClick={()=>undoMove.mutate()} disabled={undoMove.isPending}>Undo grouping correction</button></div>}
    <nav className="sticky top-3 z-20 -mx-1 overflow-x-auto rounded-control border border-line bg-canvas/95 p-1 backdrop-blur" aria-label="Investigation sections"><div className="flex min-w-max gap-1">{sectionLinks.map((item)=><Link key={item.label} to={sectionTarget(item.anchor,item.area)} className="rounded-[8px] px-3 py-2 text-xs font-semibold text-muted transition-colors hover:bg-elevated hover:text-ink focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-info" onClick={()=>window.setTimeout(()=>document.getElementById(item.anchor)?.scrollIntoView({behavior:"smooth",block:"start"}),80)}>{item.label}</Link>)}</div></nav>
    <header id="investigation-overview" className="surface-lined scroll-mt-28 p-5 sm:p-6"><div className="flex flex-col gap-5 xl:flex-row xl:items-start xl:justify-between"><div className="min-w-0 max-w-4xl"><div className="flex flex-wrap items-center gap-2"><span className="measurement-number text-xs text-muted">{value.code}</span><SeverityMark value={value.severity} /><StatusMark value={value.status} /><span className={cn("rounded-full bg-elevated px-2.5 py-1 text-xs font-semibold", (!value.environment || value.environment === "unknown") && "text-muted")} title={!value.environment || value.environment === "unknown" ? "Set the environment with Edit facts" : undefined}>{value.environment && value.environment !== "unknown" ? value.environment : "environment not set"}</span></div><h1 className="mt-3 font-heading text-3xl font-semibold tracking-[-.03em] sm:text-4xl">{value.title}</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-muted">{value.summary}</p></div><div className="flex flex-wrap gap-2"><label className="sr-only" htmlFor="direct-owner">Assign owner</label><select id="direct-owner" className="field !min-h-10 w-auto max-w-52" value={value.owner} onChange={(event)=>assign.mutate(event.target.value)} disabled={assign.isPending}>{members.data?.map((member)=><option key={member.userId} value={member.email}>Assign · {member.displayName}</option>)}{!members.data?.some((member)=>member.email===value.owner)&&<option value={value.owner}>{value.owner}</option>}</select><button className="control-secondary inline-flex items-center gap-2" onClick={() => setEditingIncident(true)}><Edit3 className="h-4 w-4" />Edit facts</button>{value.status !== "monitoring" && value.status!=="resolved" && <button className="control-secondary" onClick={() => lifecycle.mutate("start_monitoring")}>Start monitoring</button>}{value.status === "monitoring" && <button className="control-primary" onClick={() => {const next=new URLSearchParams(params);next.set("area","validate");setParams(next);window.setTimeout(()=>document.getElementById("investigation-workspace")?.scrollIntoView({behavior:"smooth",block:"start"}),80);}}>Review recovery & resolve</button>}{value.status === "resolved" && <button className="control-secondary inline-flex items-center gap-2" onClick={() => lifecycle.mutate("reopen")}><RotateCcw className="h-4 w-4" />Reopen</button>}<button className="control-quiet text-danger hover:text-danger" onClick={() => { if (window.confirm(`Delete ${value.code} and all evidence?`)) deleteIncident.mutate(); }}><Trash2 className="h-4 w-4" /></button></div></div>
      <div className="mt-5 grid gap-4 rounded-control bg-elevated p-4 lg:grid-cols-[1.2fr_1fr]"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-muted">Customer symptom / impact</p><p className="mt-1 text-sm font-semibold">{value.customerImpact || "Unknown — add a measured rate and denominator."}</p></div><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-muted">One useful next action</p>{diagnosis.isLoading ? <p className="mt-1 text-sm text-muted">Deriving from current evidence…</p> : <a className="mt-1 block text-sm font-semibold text-info hover:underline" href={diagnostic?.nextAction.href ?? "?area=investigate"}>{diagnostic?.nextAction.label ?? "Acquire timestamped evidence"}</a>}<p className="mt-1 text-xs text-muted">{diagnostic?.nextAction.reason}</p></div></div>
      <dl className="mt-5 grid gap-4 border-t border-line pt-5 sm:grid-cols-2 lg:grid-cols-5"><div><dt className="text-xs text-muted">Duration</dt><dd className="measurement-number mt-1 text-sm font-semibold">{durationBetween(value.startedAt, value.resolvedAt ?? undefined)}</dd></div><div><dt className="text-xs text-muted">Service</dt><dd className="measurement-number mt-1 text-sm">{value.service}</dd></div><div><dt className="text-xs text-muted">Owner</dt><dd className="mt-1 text-sm font-semibold">{members.data?.find((member)=>member.email===value.owner)?.displayName ?? (value.owner || "Unassigned")}</dd></div><div><dt className="text-xs text-muted">Evidence freshness</dt><dd className="measurement-number mt-1 text-sm font-semibold">{formatRelative(value.evidenceRevision ?? value.updatedAt)}</dd></div><div><dt className="text-xs text-muted">Evidence state</dt><dd className="mt-1 text-sm font-semibold capitalize">{diagnostic?.evidenceStatus ?? "checking"}</dd></div></dl>{lifecycle.error && <p role="alert" className="mt-4 text-sm text-danger">{/Evidence changed/i.test(lifecycle.error.message) ? "New evidence arrived just before your click, so nothing was changed. The page now shows the latest evidence; review it and click again." : `${lifecycle.error.message} See Fix & verify for the recovery check.`}</p>}</header>

    <section id="event-timeline" className="scroll-mt-28" aria-labelledby="timeline-title"><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><div><h2 id="timeline-title" className="section-title">Event timeline</h2><p className="mt-1 text-sm text-muted">Zoom from the complete incident into a precise window · {zoneLabel}. The evidence ledger follows the visible range.</p></div><button className="control-primary inline-flex items-center gap-2" onClick={() => setEditingEvent(null)}><Plus className="h-4 w-4" />Add observation</button></div><CausalTrace incident={value} selectedEventId={selectedEventId} onSelectEvent={selectEvent} onWindowChange={setTimelineWindow} /></section>

    <EvidenceLedger incident={value} selectedEventId={selectedEventId} visibleWindow={timelineWindow} updating={updateEvidenceState.isPending} onSelect={(eventId) => selectEvent(eventId, true)} onEdit={(event) => setEditingEvent(event)} onMove={(event) => setMovingEvent(event)} onEvidenceState={(event, state) => updateEvidenceState.mutate({ event, state })} />

    <div id="debugging-insights" className="scroll-mt-28"><DebuggingInsights incident={value} onSelectEvent={(eventId) => selectEvent(eventId, true)} /></div>
    <ResponseConsole incident={value} />
    {editingEvent !== undefined && <EventEditor incidentId={id} event={editingEvent} saving={saveEvent.isPending} error={saveEvent.error instanceof Error ? saveEvent.error.message : undefined} onCancel={() => setEditingEvent(undefined)} onSave={(draft) => saveEvent.mutate(draft)} />}
    {movingEvent && <section className="surface-lined p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="section-title">Correct automatic grouping</h2><p className="mt-1 text-sm text-muted">Preview: “{movingEvent.title}” will leave {value.code} and join the chosen investigation. Both evidence revisions and the audit trail update.</p></div><div className="flex flex-col gap-2 sm:flex-row"><select className="field min-w-64" value={targetIncidentId} onChange={(event) => setTargetIncidentId(event.target.value)}><option value="">Choose target</option>{incidentOptions.data?.filter((item) => item.id !== id && item.environment === value.environment).map((item) => <option key={item.id} value={item.id}>{item.code} · {item.title}</option>)}</select><button className="control-primary" disabled={!targetIncidentId || moveEvent.isPending} onClick={() => moveEvent.mutate()}>Confirm move</button><button className="control-quiet" onClick={() => setMovingEvent(null)}>Cancel</button></div></div>{moveEvent.error && <p className="mt-3 text-sm text-danger">{moveEvent.error.message}</p>}</section>}
    {(deleteIncident.error || updateEvidenceState.error) && <p role="alert" className="rounded-control bg-danger/10 p-3 text-sm text-danger">{(deleteIncident.error ?? updateEvidenceState.error)?.message}</p>}
    <IncidentEditor open={editingIncident} incident={value} saving={updateIncident.isPending} error={updateIncident.error instanceof Error ? updateIncident.error.message : undefined} onClose={() => setEditingIncident(false)} onSave={(draft) => updateIncident.mutate(draft)} />
  </div>;
}
